### PR TITLE
[Kohei] Modify Assignment1.java to pass the tests

### PR DESCRIPTION
**Pull request by axross**

### CODE REVIEW

**Comment by axross** [comment]
@itzderr Could you review the code, please?

**Comment by itzderr** [comment]
Looks good!

**Comment by axross** [comment]
We need to care not to merge the pull request by accident!

**Comment by axross** [comment]
I think every assignment should be on GitHub from now on, as thinking about students would find jobs haha

**Comment by itzderr** [comment]
Yeah it's better for them to use github earlier and get used to the workflow.

**Pull request closed without merging**
